export const homeObjOne = {
  id: "about",
  path1: "/",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "About Code Forum",
  headline: "Share and learn from other developers through code.",
  description:
    "This forum provides you with a platform to interact and build projects with help of your fellow devs",
  buttonLabel: "Read More",
  imgStart: false,
  img: require("../../images/img9.svg"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjTwo = {
  id: "discover",
  path1: "/",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Code Forum",
  headline: "Share and learn from other developers code",
  description:
    "This forum provides you with a platform to interact and build projects with help of your fellow devs",
  buttonLabel: "Explore",
  imgStart: true,
  img: require("../../images/img11.svg"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjThree = {
  id: "signup",
  path1: "/Register",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Sign up Today",
  headline: "Begin your journey with others",
  description:
    "This forum provides you with a platform to interact and build projects with help of your fellow devs",
  buttonLabel: "Sign up",
  imgStart: false,
  img: require("../../images/img10.svg"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjFour = {
  id: "socials",
  path1: "/",
  lightBg: false,
  path: "../Signup",
  lightText: true,
  lightTextDesc: true,
  topLine: "Social Media",
  headline: "Get intouch with other communities through our handles",
  description:
    "This forum provides you with a platform to interact and build projects with help of your fellow devs",
  buttonLabel: "Get-in Touch",
  imgStart: false,
  img: require("../../images/img12.svg"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
};
